# Generated by Django 5.2.12 on 2026-03-20 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated', 'title'],
                'indexes': [
                    models.Index(fields=['source'], name='content_source_idx'),
                    models.Index(fields=['-last_updated'], name='content_updated_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('relevant', 'Relevant'),
                            ('irrelevant', 'Irrelevant'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'content_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='flags',
                        to='content_monitoring.contentitem',
                    ),
                ),
                (
                    'keyword',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='flags',
                        to='content_monitoring.keyword',
                    ),
                ),
            ],
            options={
                'ordering': ['-last_reviewed_at', '-id'],
                'indexes': [
                    models.Index(fields=['status'], name='flag_status_idx'),
                    models.Index(fields=['keyword', 'status'], name='flag_keyword_status_idx'),
                    models.Index(fields=['content_item', 'status'], name='flag_content_status_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('keyword', 'content_item'), name='unique_keyword_content_flag'),
                ],
            },
        ),
    ]
